unit-test/main.cpp: declare cmp() before header inclusion to fix compilation
In file included from unit-test/main.cpp:6:
unit-test/../src/losertree.h: In instantiation of 'unsigned int loser_tree<T>::init_min(unsigned int) [with T = int]':
unit-test/../src/losertree.h:96:15:   required from 'loser_tree<T>::loser_tree(Iterator, Iterator)
[with Iterator = __gnu_cxx::__normal_iterator<std::pair<int*, long unsigned int>*, std::vector<std::pair<int*, long unsigned int> > >; T = int]'
unit-test/main.cpp:72:48:   required from here
unit-test/../src/losertree.h:129:10: error: 'cmp' was not declared in this scope,
and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   if (cmp(*(_streams[l].stream), *(_streams[r].stream)) <= 0) {
       ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~